platform :ios, '8.0'

pod 'PureLayout', '~> 1.1'
pod 'FLEX', '~> 1.1'
pod 'FlickrKit', '~> 1.0'
pod 'AFNetworking', '~> 2.4'
pod 'FormatterKit', '~> 1.7'
pod 'MWFeedParser'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0'
pod 'XMLDictionary', '~> 1.4'
